### ISSUE TITLE
undefined is not an object (evaluating TestFairyBridge.begin)

### ISSUE THREAD

**Issue by valinaga** [testfairy/react-native-testfairy#12]
The problem was reported before but it still persists even after removing and adding back the RCTTestFairyBridge.* files.
Any ideas how to fix this?
Im on RN: 0.44.0
Thanks.

**Comment by valinaga** [comment]
It looks like the TestFairyBridge is not found in the React.NativeModules and the class method begin is throwing an exception.
Any idea?

**Comment by vijaysharm** [comment]
I just created a new project with RN 0.45.0 and it seems to work fine for me. See sample here: https://www.dropbox.com/s/9lsb5hdhdktr2zx/AwesomeProject.zip?dl=0

If i had to take a stab at your issue, it would be that either you've changed your paths in XCode, or you didnt copy the TestFairy library as described in the [docs](https://docs.testfairy.com/Platforms/React_Native.html)

**Comment by lnpquang** [comment]
Dear, 
I have the same issue with RN 0.45.0./0.45.1
Please help to check.

Thanks.
Best regards,
LNPQuang

**Comment by lnpquang** [comment]
Dear,
I check my project.pbxproj file and AwesomeProject's project.pbxproj file, some hows lib TestFairy files are not added into project.pbxproj.
I try to add file by file again manually then it works now.

Thank you for your example project.
Best regards,
LNPQuang

**Comment by marcelkalveram** [comment]
Having the same issue here, but wasn't able to resolve it by readding the files to my project. Also tired react-native unlink/link, rnpm unlink/link, but no luck :( I always get the following error message: ```ld: library not found for -lTestFairy```

**Comment by vijaysharm** [comment]
Hello @marcelkalveram This issue only happens when you've copied the libTestFairy.a to a path where XCode cannot find it. Have a look at my project, and this screenshot of my project search path: https://www.dropbox.com/s/6kk6oween873fl8/Screen%20Shot%202017-10-15%20at%209.00.27%20AM.png?dl=0

In the above case, my libTestFairy.a is in /<root path>/<project name>/ios/libTestFairy.a. And my search path contains `$(PROJECT_DIR)`. So Xcode is able to find the library at runtime. Make sure this is the case in your project and your error should go a way.

**Comment by marcelkalveram** [comment]
@vijaysharm Thanks! That helped. I just didn't know how to configure those paths correcly.

**Comment by vijaysharm** [comment]
Hi,

I've just pushed a new version of this library (version 2.6.0) that now supports react-native link. Perhaps you should give this a try and see if it resolves your problem.
